/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/byty7Jopbe1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Comfortaa } from 'next/font/google'
import { Gabarito } from 'next/font/google'

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-background border-b px-4 py-3 md:px-6 md:py-4 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="w-6 h-6 text-primary" />
          <span className="text-lg font-bold">Acme Inc</span>
        </Link>
        <nav className="hidden md:flex items-center gap-6">
          <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
            Home
          </Link>
          <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
            Products
          </Link>
          <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
            Contact
          </Link>
        </nav>
        <Button>Download</Button>
      </header>
      <main className="flex-1">
        <section className="bg-gradient-to-b from-background to-muted py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 md:gap-16">
              <div className="space-y-6">
                <h1 className="text-4xl font-bold tracking-tighter md:text-5xl lg:text-6xl">
                  Unlock Your Digital Potential
                </h1>
                <p className="text-muted-foreground md:text-xl">
                  Discover our powerful software solutions, Solara and MantiWPF, designed to revolutionize your digital
                  experience.
                </p>
                <div className="flex gap-4">
                  <Button>Download Solara</Button>
                  <Button variant="outline">Download MantiWPF</Button>
                </div>
              </div>
              <div className="flex justify-center">
                <img
                  src="/placeholder.svg"
                  width={500}
                  height={400}
                  alt="Hero Image"
                  className="rounded-lg shadow-lg"
                  style={{ aspectRatio: "500/400", objectFit: "cover" }}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 md:gap-16">
              <div className="flex justify-center">
                <img
                  src="/placeholder.svg"
                  width={500}
                  height={400}
                  alt="Feature Image"
                  className="rounded-lg shadow-lg"
                  style={{ aspectRatio: "500/400", objectFit: "cover" }}
                />
              </div>
              <div className="space-y-6">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl">
                  Solara: Elevate Your Digital Presence
                </h2>
                <p className="text-muted-foreground md:text-xl">
                  Solara is a powerful software solution that helps you create stunning, responsive websites with ease.
                  Unlock a world of possibilities and take your online presence to new heights.
                </p>
                <Button>Download Solara</Button>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 md:gap-16">
              <div className="space-y-6">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl">MantiWPF: Streamline Your Workflow</h2>
                <p className="text-muted-foreground md:text-xl">
                  MantiWPF is a cutting-edge software solution that simplifies your workflow and boosts your
                  productivity. Experience a seamless and efficient way to manage your digital projects.
                </p>
                <Button>Download MantiWPF</Button>
              </div>
              <div className="flex justify-center">
                <img
                  src="/placeholder.svg"
                  width={500}
                  height={400}
                  alt="Feature Image"
                  className="rounded-lg shadow-lg"
                  style={{ aspectRatio: "500/400", objectFit: "cover" }}
                />
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-background border-t px-4 py-6 md:px-6 md:py-8 flex items-center justify-between">
        <p className="text-muted-foreground">&copy; 2024 Acme Inc. All rights reserved.</p>
        <div className="flex items-center gap-4">
          <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
            Privacy Policy
          </Link>
        </div>
      </footer>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
